server:
  port: 9003
spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label # Definition of the function managed by the Spring Cloud Function
    stream:
      bindings:
        packlabel-in-0: # Input binding
          destination: order-accepted # Actual name of broker that binder binds to(exchange in RabbitMQ)
          group: ${spring.application.name} # Consumer group interested in destination
        packlabel-out-0: # Output binding
          destination: order-dispatched
  config:
    import: "optional:configserver:"
    cloud:
      config:
        uri: http://localhost:8888
        request-connect-timeout: 5000 # 5s
        request-read-timeout: 5000 # 5s
        fail-fast: false # In production, set to true
        retry:
          max-attempts: 6
          initial-interval: 1000 # 1s
          max-interval: 2000 # 2s
          multiplier: 1.1


  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s